const { PERMISSIONS } = require('./permissions');
const { ROLES } = require('./roles');

module.exports.ROLE_PERMISSIONS = {
  [ROLES.SUPER]: Object.values(PERMISSIONS),

  [ROLES.APPROVER]: [
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_APPROVE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_LIST,
    PERMISSIONS.COA_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.LOCK_PERIOD,
    PERMISSIONS.INVOICE_SETTINGS
  ],

  [ROLES.SUBMITTER]: [
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_SUBMIT,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_LIST,
    PERMISSIONS.COA_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.INVOICE_SETTINGS   // submitter can view invoice settings
  ]
};
